### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by anic17** [MathInDOS/WColor#1]
Dude, share source code!
GitHub is for sharing open-source programs. Also, you used MPRESS to make it more difficult to view the program behaviour.

**Comment by MathInDOS** [comment]
> ok friend I will share 

>

**Comment by MathInDOS** [comment]
Hello, thanks to tell us your comment we will take respond.

**Comment by anic17** [comment]
Dude! It's not that difficult to share the source code of file.
You don't want to share it because there's a malware.
